name: drag_select_grid_view
description: Grid that supports both dragging and tapping to select its items.
version: 0.7.1
homepage: https://github.com/hcbpassos/drag_select_grid_view
issue_tracker: https://github.com/hcbpassos/drag_select_grid_view/issues
topics:
  - grid
  - selection
  - drag
  - widget

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
