name: drag_select_grid_view
description: Grid that supports both dragging and tapping to select its items.
version: 0.3.1
homepage: https://github.com/hugocbpassos/drag_select_grid_view
issue_tracker: https://github.com/hugocbpassos/drag_select_grid_view/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.2.4
