name: drag_select_grid_view
description: Grid that supports both dragging and tapping to select its items.
version: 0.5.0
homepage: https://github.com/hcbpassos/drag_select_grid_view
issue_tracker: https://github.com/hcbpassos/drag_select_grid_view/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.1
